FROM node:15

RUN npm install -g @angular/cli@11.2.14

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . /app

CMD ng serve --host 0.0.0.0 --disable-host-check --proxy-config proxy.conf.dev.json
EXPOSE 4200
