version: "3"
services:
  nginx:
    image: nginx
    container_name: "nginx"
    depends_on:
      - frontend
      - backend
    links:
      - backend
    volumes:
      - shared:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
  frontend:
    build:
      context: ./frontend
    container_name: "frontend"
    image: flangular_angular_frontend:latest
    volumes:
      - shared:/app/dist
  backend:
    build:
      context: ./backend
    container_name: "backend"
    image: flangular_flask_backend:latest
    ports:
      - "8000:8000"
  
volumes:
  shared: {}
