version: "3"
services:
  frontend:
    build:
      context: ./frontend
    container_name: "frontend"
    image: flangular_angular_frontend:latest
    ports:
      - "8080:80"

  backend:
    build:
      context: ./backend
    container_name: "backend"
    image: flangular_flask_backend:latest
    ports:
      - "8000:8000"
